MainWidget:

<MainWidget>:
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        BoxLayout:
            size_hint: 1, 0.3
            Button:
                text: "Button1"
        GridLayout:
            cols: 1
            Button:
                text: "Button1"
        BoxLayout:
            size_hint: 1, 0.7
            Button:
                text: "Button1"